# Default values for jmeter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

registry: quay.io/leopoldodonnell

# Before running this chart, you must create a secret in the namespace used to run JMeter
# Provice that secret here. It must have a value named "ssh". To generate this secret...
#
# kubectl create secret generic git-creds --from-file=ssh=$HOME/.ssh/id_rsa --namespace {your-namespace}
#
sshSecret: git-creds

# test defines the load test specific settings.
#
# name: is the name of the specific load test and the root name of the JMX file that will be used
# args: are the test specific arguments to send to JMeter
# repo_name: is the name of the git repository that will be found under / in jmeter master container
# repo: is the ssh specific URI for the git repository that contains the load test JMX file
# branch: is the branch from the repository to use
# testDir: is the sub directory in the repo where the JMX file will be found
# workers: is the number of workers to launch
test:
  name: supply-test-name
  repo_name: jmeter
  repo: ssh://git@bitbucket.pearson.com/pvtools/jmeter.git
  branch: feature/generalized-jmeter
  testDir: loadtest
  workers: 2
  properties:
    threads=100
    port=30012
    hub=192.168.237.69
    tdsurl=192.168.237.69
    protocol=http
    duration=7200
    uetsleep=60000
  
image:
  repository: jmeter
  tag: latest
  gitSync: gcr.io/google-containers/git-sync:v2.0.4
  pullPolicy: Always

# These are defaults you may want to change these
# resources:
#   limits:
#     cpu: 100m
#     memory: 128Mi
#   requests:
#     cpu: 100m
#     memory: 128Mi
